In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
data=pd.read_csv("UK_Accident.csv",index_col=0)

In [ ]:
data.head()

,Accident_Index,Location_Easting_OSGR,Location_Northing_OSGR,Longitude,Latitude,Police_Force,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Date,...,Pedestrian_Crossing-Physical_Facilities,Light_Conditions,Weather_Conditions,Road_Surface_Conditions,Special_Conditions_at_Site,Carriageway_Hazards,Urban_or_Rural_Area,Did_Police_Officer_Attend_Scene_of_Accident,LSOA_of_Accident_Location,Year
0,200501BS00001,525680.0,178240.0,-0.191170,51.489096,1,2,1,1,04/01/2005,...,Zebra crossing,Daylight: Street light present,Raining without high winds,Wet/Damp,NaN,NaN,1,Yes,E01002849,2005
1,200501BS00002,524170.0,181650.0,-0.211708,51.520075,1,3,1,1,05/01/2005,...,Pedestrian phase at traffic signal junction,Darkness: Street lights present and lit,Fine without high winds,Dry,NaN,NaN,1,Yes,E01002909,2005
2,200501BS00003,524520.0,182240.0,-0.206458,51.525301,1,3,2,1,06/01/2005,...,No physical crossing within 50 meters,Darkness: Street lights present and lit,Fine without high winds,Dry,NaN,NaN,1,Yes,E01002857,2005
3,200501BS00004,526900.0,177530.0,-0.173862,51.482442,1,3,1,1,07/01/2005,...,No physical crossing within 50 meters,Daylight: Street light present,Fine without high winds,Dry,NaN,NaN,1,Yes,E01002840,2005
4,200501BS00005,528060.0,179040.0,-0.156618,51.495752,1,3,1,1,10/01/2005,...,No physical crossing within 50 meters,Darkness: Street lighting unknown,Fine without high winds,Wet/Damp,NaN,NaN,1,Yes,E01002863,2005

In [ ]:
data.drop("Accident_Index",axis=1,inplace=True)

In [ ]:
data.head()

,Location_Easting_OSGR,Location_Northing_OSGR,Longitude,Latitude,Police_Force,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Date,Day_of_Week,...,Pedestrian_Crossing-Physical_Facilities,Light_Conditions,Weather_Conditions,Road_Surface_Conditions,Special_Conditions_at_Site,Carriageway_Hazards,Urban_or_Rural_Area,Did_Police_Officer_Attend_Scene_of_Accident,LSOA_of_Accident_Location,Year
0,525680.0,178240.0,-0.191170,51.489096,1,2,1,1,04/01/2005,3,...,Zebra crossing,Daylight: Street light present,Raining without high winds,Wet/Damp,NaN,NaN,1,Yes,E01002849,2005
1,524170.0,181650.0,-0.211708,51.520075,1,3,1,1,05/01/2005,4,...,Pedestrian phase at traffic signal junction,Darkness: Street lights present and lit,Fine without high winds,Dry,NaN,NaN,1,Yes,E01002909,2005
2,524520.0,182240.0,-0.206458,51.525301,1,3,2,1,06/01/2005,5,...,No physical crossing within 50 meters,Darkness: Street lights present and lit,Fine without high winds,Dry,NaN,NaN,1,Yes,E01002857,2005
3,526900.0,177530.0,-0.173862,51.482442,1,3,1,1,07/01/2005,6,...,No physical crossing within 50 meters,Daylight: Street light present,Fine without high winds,Dry,NaN,NaN,1,Yes,E01002840,2005
4,528060.0,179040.0,-0.156618,51.495752,1,3,1,1,10/01/2005,2,...,No physical crossing within 50 meters,Darkness: Street lighting unknown,Fine without high winds,Wet/Damp,NaN,NaN,1,Yes,E01002863,2005

In [ ]:
total_row=data.shape[0]

In [ ]:
data_null=data.isnull().sum()[data.isnull().sum() > 0]

In [ ]:
data_null

Location_Easting_OSGR                          101
Longitude                                      101
Time                                           117
Junction_Control                            602835
Pedestrian_Crossing-Human_Control               17
Pedestrian_Crossing-Physical_Facilities         34
Special_Conditions_at_Site                 1467568
Carriageway_Hazards                        1476900
LSOA_of_Accident_Location                   108238
dtype: int64

In [ ]:
data_null_percentage=(data_null/total_row)*100

In [ ]:
data_null_percentage

Location_Easting_OSGR                       0.006715
Longitude                                   0.006715
Time                                        0.007778
Junction_Control                           40.078117
Pedestrian_Crossing-Human_Control           0.001130
Pedestrian_Crossing-Physical_Facilities     0.002260
Special_Conditions_at_Site                 97.567929
Carriageway_Hazards                        98.188346
LSOA_of_Accident_Location                   7.195958
dtype: float64

In [ ]:
data['Junction_Control'].value_counts()

Junction_Control
Giveway or uncontrolled     733940
Automatic traffic signal    155717
Stop Sign                     9179
Authorised person             2479
Name: count, dtype: int64

In [ ]:
data['Special_Conditions_at_Site'].value_counts()

Special_Conditions_at_Site
Roadworks                                          17223
Ol or diesel                                        5243
Mud                                                 4610
Road surface defective                              3664
Auto traffic singal out                             2788
Permanent sign or marking defective or obscured     2269
Auto traffic signal partly defective                 785
Name: count, dtype: int64

In [ ]:
data['Carriageway_Hazards'].value_counts()

Carriageway_Hazards
Other object in carriageway                11762
Any animal (except a ridden horse)          8014
Pedestrian in carriageway (not injured)     3586
Involvement with previous accident          2282
Dislodged vehicle load in carriageway       1606
Name: count, dtype: int64

In [ ]:
data['LSOA_of_Accident_Location'].value_counts()

LSOA_of_Accident_Location
E01000004    2074
E01011365    1337
E01004736    1274
E01008440    1034
E01005131     872
             ...
E01000584       1
E01010390       1
W01001284       1
E01027270       1
E01025685       1
Name: count, Length: 35452, dtype: int64

In [ ]:
Colums_to_drop=data_null_percentage[data_null_percentage>30].index

In [ ]:
Colums_to_drop

Index(['Junction_Control', 'Special_Conditions_at_Site',
       'Carriageway_Hazards'],
      dtype='object')

In [ ]:
new_data=data.drop(Colums_to_drop,axis=1)
new_data.dropna(inplace=True)

In [ ]:
new_data.head()

,Location_Easting_OSGR,Location_Northing_OSGR,Longitude,Latitude,Police_Force,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Date,Day_of_Week,...,2nd_Road_Number,Pedestrian_Crossing-Human_Control,Pedestrian_Crossing-Physical_Facilities,Light_Conditions,Weather_Conditions,Road_Surface_Conditions,Urban_or_Rural_Area,Did_Police_Officer_Attend_Scene_of_Accident,LSOA_of_Accident_Location,Year
0,525680.0,178240.0,-0.191170,51.489096,1,2,1,1,04/01/2005,3,...,0,None within 50 metres,Zebra crossing,Daylight: Street light present,Raining without high winds,Wet/Damp,1,Yes,E01002849,2005
1,524170.0,181650.0,-0.211708,51.520075,1,3,1,1,05/01/2005,4,...,0,None within 50 metres,Pedestrian phase at traffic signal junction,Darkness: Street lights present and lit,Fine without high winds,Dry,1,Yes,E01002909,2005
2,524520.0,182240.0,-0.206458,51.525301,1,3,2,1,06/01/2005,5,...,0,None within 50 metres,No physical crossing within 50 meters,Darkness: Street lights present and lit,Fine without high winds,Dry,1,Yes,E01002857,2005
3,526900.0,177530.0,-0.173862,51.482442,1,3,1,1,07/01/2005,6,...,0,None within 50 metres,No physical crossing within 50 meters,Daylight: Street light present,Fine without high winds,Dry,1,Yes,E01002840,2005
4,528060.0,179040.0,-0.156618,51.495752,1,3,1,1,10/01/2005,2,...,0,None within 50 metres,No physical crossing within 50 meters,Darkness: Street lighting unknown,Fine without high winds,Wet/Damp,1,Yes,E01002863,2005

In [ ]:
new_data.columns[new_data.isnull().sum()>0]

Index([], dtype='object')

In [ ]:
new_data.isnull().sum()

Location_Easting_OSGR                          0
Location_Northing_OSGR                         0
Longitude                                      0
Latitude                                       0
Police_Force                                   0
Accident_Severity                              0
Number_of_Vehicles                             0
Number_of_Casualties                           0
Date                                           0
Day_of_Week                                    0
Time                                           0
Local_Authority_(District)                     0
Local_Authority_(Highway)                      0
1st_Road_Class                                 0
1st_Road_Number                                0
Road_Type                                      0
Speed_limit                                    0
2nd_Road_Class                                 0
2nd_Road_Number                                0
Pedestrian_Crossing-Human_Control              0
Pedestrian_Crossing-Physical_Facilities        0
Light_Conditions                               0
Weather_Conditions                             0
Road_Surface_Conditions                        0
Urban_or_Rural_Area                            0
Did_Police_Officer_Attend_Scene_of_Accident    0
LSOA_of_Accident_Location                      0
Year                                           0
dtype: int64

In [ ]:
percent_of_data_remaining_row=(new_data.shape[0]/data.shape[0])*100

In [ ]:
percent_of_data_remaining_column=(new_data.shape[1]/data.shape[1])*100

In [ ]:
print(f"Row Percentage of data remaining after cleaning: {percent_of_data_remaining_row:.2f}%")
print(f"Column Percentage of data remaining after cleaning: {percent_of_data_remaining_column:.2f}%")

Row Percentage of data remaining after cleaning: 92.80%
Column Percentage of data remaining after cleaning: 90.32%

In [ ]:
new_data.sort_values('Date', ascending=True, inplace=True)

In [ ]:
new_data['Date'].info

<bound method Series.info of 73757     01/01/2005
28712     01/01/2005
44088     01/01/2005
178604    01/01/2005
153400    01/01/2005
             ...
438584    31/12/2014
370699    31/12/2014
370698    31/12/2014
429012    31/12/2014
321931    31/12/2014
Name: Date, Length: 1395848, dtype: object>

In [ ]:
new_data["Date"] = pd.to_datetime(new_data["Date"], dayfirst=True)  # skip if already datetime
new_data["Month"] = new_data["Date"].dt.month  
new_data["Month_Name"] = new_data["Date"].dt.month_name()
new_data["Quarter"] = new_data["Date"].dt.quarter

In [ ]:
new_data

,Location_Easting_OSGR,Location_Northing_OSGR,Longitude,Latitude,Police_Force,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Date,Day_of_Week,...,Light_Conditions,Weather_Conditions,Road_Surface_Conditions,Urban_or_Rural_Area,Did_Police_Officer_Attend_Scene_of_Accident,LSOA_of_Accident_Location,Year,Month,Month_Name,Quarter
73757,489190.0,411320.0,-0.653980,53.590872,16,3,2,1,2005-01-01,7,...,Darkness: Street lights present and lit,Raining without high winds,Wet/Damp,1,Yes,E01013330,2005,1,January,1
28712,331080.0,436670.0,-3.048444,53.821714,4,3,1,1,2005-01-01,7,...,Darkness: Street lights present and lit,Fine without high winds,Wet/Damp,1,Yes,E01012681,2005,1,January,1
44088,371650.0,410000.0,-2.429732,53.585807,6,3,2,3,2005-01-01,7,...,Darkness: Street lights present and lit,Fine without high winds,Wet/Damp,1,Yes,E01004821,2005,1,January,1
178604,310730.0,195090.0,-3.291670,51.647449,61,2,1,2,2005-01-01,7,...,Daylight: Street light present,Raining with high winds,Wet/Damp,1,Yes,W01001379,2005,1,January,1
153400,530810.0,105350.0,-0.143808,50.832843,47,3,1,1,2005-01-01,7,...,Darkness: Street lights present and lit,Raining without high winds,Wet/Damp,1,Yes,E01016938,2005,1,January,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
438584,541973.0,131906.0,0.024960,51.068871,47,2,2,1,2014-12-31,4,...,Darkness: Street lights present and lit,Fine without high winds,Wet/Damp,2,Yes,E01021168,2014,12,December,4
370699,415383.0,420370.0,-1.768590,53.679565,13,2,1,1,2014-12-31,4,...,Darkness: Street lights present and lit,Fine without high winds,Wet/Damp,1,Yes,E01011102,2014,12,December,4
370698,405698.0,423377.0,-1.915161,53.706786,13,2,2,2,2014-12-31,4,...,Darkness: Street lights present and lit,Fine without high winds,Wet/Damp,1,Yes,E01010979,2014,12,December,4
429012,493756.0,141683.0,-0.660441,51.166659,45,2,1,1,2014-12-31,4,...,Daylight: Street light present,Fine without high winds,Frost/Ice,2,Yes,E01030939,2014,12,December,4
321931,529300.0,183670.0,-0.137069,51.537079,1,3,1,1,2014-12-31,4,...,Darkness: Street lights present and lit,Fine without high winds,Wet/Damp,1,Yes,E01000958,2014,12,December,4

In [ ]:
# Save the cleaned data to different formats
#new_data.to_csv("cleaned_uk_accident_data.csv", index=False)
#new_data.to_parquet('output_file_name.parquet')
#new_data.to_hdf('output_file_name.h5', key='df', mode='w')
#new_data.to_feather('output_file_name.feather')